# Generated by Django 3.2.8 on 2021-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
