# Generated by Django 3.2.8 on 2021-12-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_signupdata_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupdata',
        ),
    ]
